### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by chrisafennell**
Problem installing this package through composer. This should solve the issue.

### CODE REVIEW

**Comment by kalley** [comment]
Would this work with using `3.0.x`? I'd rather have it tied to a version rather than a dev branch.

**Comment by chrisafennell** [comment]
That would probably work.

**Comment by kalley** [comment]
Actually, I'll just go with it. Thanks for the PR!

**Comment by chrisafennell** [comment]
Anytime! Thanks!

**Pull request merged**
